project:
  type: website

website:
  navbar:
    left:
      - text: "About me"
        href: index.qmd
      - text: "Computer Science"
        href: computer-science.qmd
      - text: "My Hungarian Thoughts"
        href: hungarian-thoughts.qmd